image: mcr.microsoft.com/dotnet/core/sdk:3

stages:
    - build
    - test

variables:
    test: "Example.Test"

build:
    stage: build
    script:
        - "dotnet restore"
        - "dotnet build"

test:
    stage: test
    script:
        - "cd $test"
        - "dotnet test"